import { StyleSheet } from 'react-native';

export const modalStyles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  absolute: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  modalView: {
    position: 'absolute',
    justifyContent: 'space-between',
    bottom: 0,
    width: '100%',
    height: '70%',
    backgroundColor: 'black',
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: '#F194FF',
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    fontFamily: 'Outfit-Regular',
    textAlign: 'justify',
    fontSize: 18,
    color: '#F2AE7F',
  },
  header: {
    fontSize: 20,
    color: '#E86A33',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  buttonWhite: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    alignSelf: 'center',
    paddingHorizontal: 50,
    paddingVertical: 15,
    backgroundColor: '#ffffff',
    borderRadius: 50,
    marginTop: 20,
  },
  buttonGreen: {
    alignSelf: 'center',
    paddingHorizontal: 50,
    paddingVertical: 15,
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#06753b',
    borderRadius: 50,
    marginTop: 20,
  },
  actionButton: {
    alignSelf: 'center',
    backgroundColor: 'white',
    paddingHorizontal: 50,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: '#06753b',
    borderRadius: 50,
    marginTop: 20,
  },
  buttonText: {
    fontSize: 20,
    fontFamily: 'Outfit-Light',
    color: '#06753b',
    textAlign: 'center',
  },
  resultText: {
    fontSize: 20,
    fontFamily: 'Outfit-Regular',
    color: '#E86A33',
    textAlign: 'center',
  },
});
