/* 🤖 this file was generated by svg-to-ts */
export const icons: { [key in MyIconType]: string } = {
  qrIcon:
    '<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="none"><path fill="#FEF5EE" d="M21.667 23.333v-1.666h-5v-5h5V20H25v3.333h-1.667v3.334H20V30h-3.333v-5H20v-1.667zM30 30h-6.667v-3.333h3.334v-3.334H30zM0 0h13.333v13.333H0zm3.333 3.333V10H10V3.333zM16.667 0H30v13.333H16.667zM20 3.333V10h6.667V3.333zM0 16.667h13.333V30H0zM3.333 20v6.667H10V20zM25 16.667h5V20h-5zM5 5h3.333v3.333H5zm0 16.667h3.333V25H5zM21.667 5H25v3.333h-3.333z"/></svg>',
  pngIcon:
    '<svg xmlns="http://www.w3.org/2000/svg" width="34" height="31" fill="none"><path fill="#FEF5EE" d="m5.047 30-.034.033L4.978 30H1.987a1.655 1.655 0 0 1-1.654-1.655V1.655A1.667 1.667 0 0 1 1.987 0h30.026c.914 0 1.654.742 1.654 1.655v26.69A1.666 1.666 0 0 1 32.013 30zm25.286-10V3.333H3.667v23.334L20.333 10zm0 4.713-10-10L8.38 26.667h21.953zm-20-11.38a3.333 3.333 0 1 1 0-6.667 3.333 3.333 0 0 1 0 6.667"/></svg>',
};
export type MyIconType = 'qrIcon' | 'pngIcon';
